# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca36c4897612fa3b5c54bf66c8706ceb5f8c98ac60879ebf9c6d6b2b767debb7f050524d0ac06a72db1b06656e08a8f05a817a5d2cc625c17711802050a47a33

test:
  secret_key_base: 78cd27f5fc079c36224c0c1299911314ebc8699171dc3ba910807558669551222e5c6c57eba9dda0ed92c92e02a0b9e0f764f0aea27dddbe9fd410330eec74cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
